### ISSUE TITLE
RequiredItem doesn't work

### ISSUE THREAD

**Issue by tschaffter** [Phiwa/DragonTravel#16]
I enabled the required item 122 (dragon egg) to fly to stations.
	  
RequiredItem:
  Item: 122
  For:
    toStation: true
	
Then when I enter /dt travel <station> without having the egg on me, I get the in-game message:

An internal error occured while attempting to perform this command

![2015-04-01_08 41 42](https://cloud.githubusercontent.com/assets/3056480/6936023/d369d1a8-d84d-11e4-9307-776adfa2a7fc.png)

[08:41:43] [Server thread/INFO]: tschaffter issued server command: /dt travel test
[08:41:43] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dt' in plugin DragonTravel vPhoenix v0.0.1.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_33]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_33]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_33]
Caused by: java.lang.IllegalArgumentException: Material cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at org.bukkit.craftbukkit.v1_8_R2.inventory.CraftInventory.contains(CraftInventory.java:92) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        at eu.phiwa.dt.movement.Travels.toStation(Travels.java:258) ~[?:?]
        at eu.phiwa.dt.commands.CommandHandler.onCommand(CommandHandler.java:451) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.3.jar:git-Spigot-26dfd01-ad2f806]
        ... 15 more
		
The same error occurs when I have the dragon egg in my inventory.

**Comment by esmic** [comment]
i have exacly the same problem, but also with payment by items

**Comment by Phiwa** [comment]
Which version of DragonTravel do you run?

**Comment by esmic** [comment]
im esmic on the bukkit forums also. posting in this thread http://dev.bukkit.org/bukkit-plugins/dragontravel/tickets/230-failure-to-use-required-items-and-payment-by-items/

here is screenshot from today 
![dt](https://cloud.githubusercontent.com/assets/3235640/9775864/13063dc2-5753-11e5-97de-515823e90427.png)

**Comment by Phiwa** [comment]
@tschaffter Totally forgot about this issue. Fixed it in commit fc2a7ac9f2ad93a1a34d5e544b0ba7467abc14d3, will be included in next release.

**Comment by tschaffter** [comment]
Thanks! 👍
