### ISSUE TITLE
paper 1.12.2 Cannot enable.

### ISSUE THREAD

**Issue by nozuo** [Phiwa/DragonTravel#52]
[11:58:34] [Server thread/INFO]: [DragonTravel] Enabling DragonTravel v01.007.02
[11:58:34] [Server thread/INFO]: [DragonTravel] [Error] Could not register the RyeDragon-entity!
[11:58:34] [Server thread/WARN]: java.lang.RuntimeException: Unable to override the old entity RegistryMaterials
[11:58:34] [Server thread/WARN]: 	at eu.phiwa.dragontravel.nms.v1_12_R1.CustomEntityRegistry.getInstance(CustomEntityRegistry.java:55)
[11:58:34] [Server thread/WARN]: 	at eu.phiwa.dragontravel.nms.v1_12_R1.CustomEntityRegistry.registerCustomEntity(CustomEntityRegistry.java:62)
[11:58:34] [Server thread/WARN]: 	at eu.phiwa.dragontravel.nms.v1_12_R1.EntityRegister.registerEntity(EntityRegister.java:12)
[11:58:34] [Server thread/WARN]: 	at eu.phiwa.dragontravel.core.DragonTravel.onEnable(DragonTravel.java:132)
[11:58:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:58:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[11:58:34] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:58:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[11:58:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[11:58:34] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[11:58:34] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[11:58:34] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[11:58:34] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[11:58:34] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[11:58:34] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:58:34] [Server thread/WARN]: Caused by: java.lang.IllegalAccessException: Can not set static final net.minecraft.server.v1_12_R1.RegistryMaterials field net.minecraft.server.v1_12_R1.EntityTypes.b to eu.phiwa.dragontravel.nms.v1_12_R1.CustomEntityRegistry
[11:58:34] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
[11:58:34] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
[11:58:34] [Server thread/WARN]: 	at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
[11:58:34] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Field.java:764)
[11:58:34] [Server thread/WARN]: 	at eu.phiwa.dragontravel.nms.v1_12_R1.CustomEntityRegistry.getInstance(CustomEntityRegistry.java:51)
[11:58:34] [Server thread/WARN]: 	... 14 more
[11:58:34] [Server thread/INFO]: [DragonTravel] Disabling DragonTravel v01.007.02
[11:58:34] [Server thread/INFO]: [DragonTravel] -----------------------------------------------
[11:58:34] [Server thread/INFO]: [DragonTravel] Successfully disabled DragonTravel 01.007.02
[11:58:34] [Server thread/INFO]: [DragonTravel] -----------------------------------------------

**Comment by Phiwa** [comment]
I'm currently on holidays, but will look into it as soon as I return at the end of August.
