### ISSUE TITLE
1.18.2 update

### ISSUE THREAD

**Issue by XXX10Tacles** [Phiwa/DragonTravel#85]
Plugin does not work on 1.18.2. It needs to be updated.

here is error as well: 
`[06:28:09 WARN]: eu.phiwa.com.sk89q.minecraft.util.commands.WrappedCommandException: java.lang.NullPointerException: Cannot invoke "eu.phiwa.dragontravel.core.hooks.payment.PaymentManager.chargePlayer(eu.phiwa.dragontravel.core.hooks.payment.ChargeType, org.bukkit.entity.Player)" because the return value of "eu.phiwa.dragontravel.core.DragonTravel.getPaymentManager()" is null
[06:28:09 WARN]:        at DragonTravel-01.008.02.jar//eu.phiwa.com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:543)
[06:28:09 WARN]:        at DragonTravel-01.008.02.jar//eu.phiwa.com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:520)
[06:28:09 WARN]:        at DragonTravel-01.008.02.jar//eu.phiwa.com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:475)
[06:28:09 WARN]:        at DragonTravel-01.008.02.jar//eu.phiwa.com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:409)
[06:28:09 WARN]:        at DragonTravel-01.008.02.jar//eu.phiwa.dragontravel.core.DragonTravel.onCommand(DragonTravel.java:80)
[06:28:09 WARN]:        at DragonTravel-01.008.02.jar//eu.phiwa.com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:51)
[06:28:09 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[06:28:09 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[06:28:09 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2390)
[06:28:09 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[06:28:09 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2182)
[06:28:09 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[06:28:09 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[06:28:09 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[06:28:09 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[06:28:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[06:28:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[06:28:09 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1427)
[06:28:09 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[06:28:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[06:28:09 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1404)
[06:28:09 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1397)
[06:28:09 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bo(IAsyncTaskHandler.java:114)
[06:28:09 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1531)
[06:28:09 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1247)
[06:28:09 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[06:28:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[06:28:09 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "eu.phiwa.dragontravel.core.hooks.payment.PaymentManager.chargePlayer(eu.phiwa.dragontravel.core.hooks.payment.ChargeType, org.bukkit.entity.Player)" because the return value of "eu.phiwa.dragontravel.core.DragonTravel.getPaymentManager()" is null
[06:28:09 WARN]:        at DragonTravel-01.008.02.jar//eu.phiwa.dragontravel.core.commands.DragonTravelCommands.startCoordsTravel(DragonTravelCommands.java:565)
[06:28:09 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:28:09 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[06:28:09 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:28:09 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[06:28:09 WARN]:        at DragonTravel-01.008.02.jar//eu.phiwa.com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:533)
[06:28:09 WARN]:        ... 26 more`

server version: Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Purpur-1428 (MC: 1.17.1)
* I am running the latest version

**Comment by Phiwa** [comment]
First of all sorry for the late response...

You are right, the plugin is indeed not compatible with 1.18 at all. Since it is an NMS-based plugin, it requires an update for each version of MC/CB/Spigot.

I haven't worked on this project for a long time though and the last version was released in July 2021. Since I stopped playing Minecraft about 8 years ago, I'm not sure if I will ever release another version bringing compatibility with MC 1.18 in the future.

I'm sorry that I do not have better news...
